import { News } from './news';

export const NEWS: News[] = [ // stworzony array z informacją niezbędną dla korzystania z danej strony, zawiera informacje o nowinach
// tslint:disable-next-line: max-line-length
    {name: 'official: booml4 joins na`vi', description1: 'Rosyjski gracz dołącza do Na`Vi w porozumieniu, w którym weteran Ioann „Edward” Sukhariev łączy się z Winstrike, stając się pierwszym sygnatariuszem gigantów CIS w ciągu 18 miesięcy, odkąd Denis „elektronic” Szaripow został zatrudniony z FlipSid3 w listopadzie 2017 roku.', description2: 'Boombl4 dokonał przełomu w 2017 roku, kiedy podpisał kontrakt z EPG w czasie, gdy był praktycznie nieznany. Trzon tego zespołu dołączył do Quantum Bellator Fire, który podniósł się na początku 2018 r. W fazie playoff w ELEAGUE Major Boston po przejściu przez CIS Minor.', photoOfNews: 'assets/news/newscard1.jpg'} ,
// tslint:disable-next-line: max-line-length
    {name: 'edward dołaczył do winstrike', description1: 'Winstrike ogłosił, że zakończył podpisywanie pożyczki Ioann „Edward” Sukhariev z Natus Vincere.', description2: 'Ukraiński weteran wypełni rolę lidera w drużynie, która pozostała pusta po przejściu Kirilla „Boombl4” Mikhailov do Na`vi. Dla Edwarda będzie to jego pierwsza zmiana scenerii od 2013 roku, kiedy wrócił do Natus Vincere po graniu dla Astana Dragons przez około cztery miesiące. Podczas pobytu w Na`Vi, zdobył kilka zwycięstw tytułowych, w szczególności na ESL One New York 2016 i ESL One Kolonia 2018, i osiągnął wielki finał w trzech różnych kategoriach.', photoOfNews: 'assets/news/newscard13.jpg'},
// tslint:disable-next-line: max-line-length
    {name: 'cis esports turniej już ogłoszony', description1: 'CIS Esports League współpracuje z Danylo „Zeus” Teslenko i AVANGAR, aby rozpocząć pierwszy sezon Mistrzostw CIS Esports, który obejmie 30 000$ nagród pieniężnych.', description2: 'Mistrzostwa półprofesjonalne będą miały 64 zespoły, przy czym do 32 najlepszych z pierwszego etapu dołączyły 24 zaproszone strony i osiem dodatkowych drużyn przyjętych przez specjalny formularz zgłoszeniowy. Główny turniej - Pro Championship - będzie składał się z 16 drużyn i będzie miał szwajcarską fazę, a następnie pojedynczą eliminację, najlepsze trzy mecze.', photoOfNews: 'assets/news/newscard2.jpg'},
// tslint:disable-next-line: max-line-length
    {name: 'liquid zakończyli esl one cologne 2019', description1: 'Po zwycięstwie 2:0 nad G2 w wielkim finale GG.BET Cologne Invitational, Liquid zapewnił sobie miejsce na ESL One Cologne 2019.', description2: 'Wielki finał GG.BET Cologne Invitational pokazał, że Liquid zwycięża na mapie Overpass. Liquid rozpoczeli atak, dominując zarówno na wczesnych, jak i środkowych etapach połowy, zapewniając prowadzenie 7-3. W kierunku ostatnich etapów G2 znalazło oparcie, doprowadzając deficyt do trzech rund do końca połowy.', photoOfNews: 'assets/news/newscard3.jpg'},
// tslint:disable-next-line: max-line-length
    {name: 'renegades dołaczyli do listy uczęstników blast pro series los angeles', description1: 'Renegades przyjęli zaproszenie do rywalizacji w BLAST Pro Series Los Angeles, ogłosili organizatorzy wydarzeń.', description2: 'Australijscy graczy wezmą udział w finałowym turnieju o wartości 250 000$, dołączając do kolejnego zaproszenia dzikich kart w NRG i czterech drużynach obwodowych - FaZe, MIBR, Liquid i Cloud9. Będzie to pierwszy w historii BLAST Pro Series dla Renegades, którzy będą chcieli ponownie wejść do pierwszej dziesiątki rankingu po osiągnięciu najwyższej w historii pozycji piątej w kwietniu.', photoOfNews: 'assets/news/newscard4.jpg'},
// tslint:disable-next-line: max-line-length
    {name: 'esl pro league 10 regular season ogłoszone', description1: 'ESL ogłosił dni rozgrywek etapów grupowych ESL Pro League Sezon 10, które potrwają od 8 października do 18 listopada.', description2: 'Dziesiąty sezon ESL Pro League będzie przebiegał według tego samego, przerobionego obecnie formatu dla Sezonu 9, z dwoma etapami w grupie offline w głównych regionach, Europie i obu Amerykach. Pierwsza faza grupowa sezonu regularnego rozpocznie się 8 października, a zakończy 19 października, a każda z czterech grup obejmuje trzy dni.', photoOfNews: 'assets/news/newscard5.jpg'},
// tslint:disable-next-line: max-line-length
    {name: 'nazwano uczęstników na`vi esports', description1: 'Natus Vincere ujawnił dziesięciu uczestników, którzy zostali wybrani do wzięcia udziału w Esports.', description2: 'Na początku maja Natus Vincere ogłosił projekt Na`Vi Esports Camp, mający na celu sprawdzenie pięciu młodych talentów w składzie akademii organizacji, Na`Vi.Junior. Po zakończeniu procesu selekcji, który rozpoczął się 6 maja, pojawiło się dziesięciu kandydatów do bootcampu. Imi zostali: Alexey "Topa" Topchienko, Rodion "fear" Smyk, Andrey "Whitesmith" Saribekyan, Ivan "kapacho" Koplenko, Valeriy "B1t" Vakhovskiy, Kirill "Gospadarov" Gospadarov, Kirill "poka " Starovoytov, Vyacheslav "Art1st" Lyadnov, Daniil "Porya" Poryadin,Eugene "Aunkere" Karyat', photoOfNews: 'assets/news/newscard6.jpg'},
// tslint:disable-next-line: max-line-length
    {name: 'zywoo został mvp ecs season 7 finals', description1: 'Zdeklasowanie konkurencji podczas finałów 7 sezonu ECS, Mathieu "ZywOo" Herbaut zdobył swoją drugą nagrodę Most Valuable Player od HLTV.org i betway na londyńskim turnieju.', description2: '18-latek pokazał najwyższy poziom w trakcie turnieju o 500 000$, prowadząc Vitality do drugiego tytułu w ostatnich trzech występach ze średnią oceną 1,41 na 10 rozegranych mapach. W fazie grupowej ZywOo zaczął ustanawiać swoje roszczenia z pięcioma z sześciu map ocenionych powyżej 1,00, ponieważ Vitality wygrał dwa zwycięstwa nad Complexity i poniósł stratę przeciw North, ale gdy ECS dotarł do fazy playoff, nie było żadnego konkurencji.', photoOfNews: 'assets/news/newscard7.jpg'},
// tslint:disable-next-line: max-line-length
    {name: 'aristocracy wygrali esl polish championship spring', description1: 'Aristocracy pokonali Virtus.pro 2-0 w wielkim finale, by zdobyć trofeum finałowe Mistrzostw Polski ESL Wiosna 2019 (16-14 na Mirage i 16-5 na Nuke).', description2: 'W wydarzeniu LAN odbywającym się w ESL Arena w Katowicach wzięło udział sześć najlepszych drużyn z internetowego etapu konkursu. Arystokracja i X-kom zakwalifikowały się bezpośrednio do półfinałów, ponieważ zakończyły rozgrywki w pierwszej dwójce w fazie online, podczas gdy pozostałe cztery strony rozpoczęły kampanię w ćwierćfinale. ', photoOfNews: 'assets/news/newscard8.jpg'},
// tslint:disable-next-line: max-line-length
    {name: 'valiance zmienili nazwe na cr4azy', description1: 'Organizacja znana wcześniej jako Valiance, siedząc obecnie #17 na świecie, zmieniła nazwę na CR4ZY.', description2: 'Po podpisaniu pod koniec 2017 r. Serbskiej listy Binary Dragons, Valiance stało się domową nazwą po kilku zmianach składu, które obejmowały wprowadzenie Nemanji „nexa” Isakovića, Rokasa „EspiranTo” Milasauskasa i Otto „ottoNd” Sihvo, którzy dołączyli do dwóch pozostałych oryginalnych graczy Nemanja „huNter” Kovač i Nestor „LETN1” Tanić jako Luka „emi” Vuković przyjęli obowiązki trenerskie.', photoOfNews: 'assets/news/newscard9.jpg'},
// tslint:disable-next-line: max-line-length
    {name: 'astralis dostali zaproszenie na esl one new york', description1: 'ESL ogłosił, że Astralis przyjęli zaproszenie do wzięcia udziału w tegorocznym ESL One w Nowym Jorku.', description2: 'Duńscy gigancy to pierwszy zespół potwierdzony na turnieju w Ameryce Północnej, który odbędzie się w dniach 26-29 września w Barclays Center, z nagrodą 200 000$. To będzie trzeci raz, kiedy Astralis będą obecni na turnieju ESL One New York, a Duńczycy przegapili tylko zeszłoroczną edycję. W 2016 r. Wyszli na scenę szwajcarską z rekordem 1-3, podczas gdy w następnym roku zostali wysłani do fazy grupowej z podwójną eliminacją.', photoOfNews: 'assets/news/newscard10.jpg'},
// tslint:disable-next-line: max-line-length
    {name: 'liquid dostali 1 pozycję w rankingu swiatowym', description1: 'Liquid pokonali Astralis na szczycie światowego rankingu po niedzielnym zwycięstwie w DreamHack Masters Dallas.', description2: 'Strona północnoamerykańska trafiła na szczyt po raz pierwszy w historii organizacji po najnowszej aktualizacji rankingu, osiągając idealne 1000 punktów dzięki dwóm zwycięskim kampaniom, z których ostatnia w DreamHack Masters Dallas. Astralis opuscili miejsce nr 1 po 406 dniach na szczycie - najdłuższe panowanie od wprowadzenia rankingu w 2015 roku.', photoOfNews: 'assets/news/newscard11.jpg'},
// tslint:disable-next-line: max-line-length
    {name: 'mibr, vitality dotarli na iem chicago 2019', description1: 'MIBR i Vitality otrzymały zaproszenia na IEM Chicago, które odbędą się w dniach 18-21 lipca.', description2: 'Obie strony dołączają do wcześniej zaproszonego duetu, Liquid i ENCE, jako trzecie i czwarte zaproszone zespoły do turnieju 250 000$, z dodatkowymi dwoma zaproszeniami jeszcze do ogłoszenia. Ostatnie dwa miejsca będą dostępne do zdobycia w kwalifikacjach w Ameryce Północnej i Europie.', photoOfNews: 'assets/news/newscard12.jpg'},
// tslint:disable-next-line: max-line-length
    {name: 'neo dołaczył do faze', description1: 'FaZe dopełniło dodanie Filipa „NEO” Kubskiego do ich spisu, zamiast Dauren „AdreN” Kystaubayeva, organizacja ogłosiła w mediach społecznościowych.', description2: 'W oświadczeniu stwierdza się, że NEO przejmuje rolę zastępcy, ale po dalszych wyjaśnieniach Nikola „NiKo” Kovač potwierdził, że Polak przechodzi obecnie okres próbny w kadrze europejskiej. Weteran weźmie także udział w grze w zespole, co FaZe zamierzało wypełnić od czasu wyjazdu Finna „karrigana” Andersena pod koniec 2018 roku.', photoOfNews: 'assets/news/newscard14.jpg'},
// tslint:disable-next-line: max-line-length
    {name: 'nickelbak dołaczył do pro100', description1: 'pro100 sfinalizowali swój plan z dodatkiem Alexeya „NickelBack” Trofimova.', description2: 'Po odejściu Dima „def” Lemeshchuka i Wiaczesława „Art1st” Lyadnova na początku kwietnia lista startowa pro100 rozpadła się, pozostawiając zaledwie trzech członków. Aby zrekompensować niedobór składu, długoterminowy przedstawiciel Leonard „kenzor” Wołodarchuk został sprowadzony z ławki, a NickelBack został dodany tymczasowo, występując wraz z grafikiem w kilku turniejach online.', photoOfNews: 'assets/news/newscard15.jpg'}
];
